[template]
src = "jaeger.boot.tmpl"
dest = "/opt/minion/etc/featuresBoot.d/jaeger.boot"
keys = [
    "/tracing"
]
reload_cmd = "/opt/minion/confd/scripts/remove-if-empty /opt/minion/etc/featuresBoot.d/jaeger.boot"
