[template]
src = "org.opennms.features.telemetry.listeners-udp-single-port.cfg.tmpl"
dest = "/opt/minion/etc/org.opennms.features.telemetry.listeners-udp-single-port.cfg"
keys = [
    "/telemetry/flows"
]
reload_cmd = "/opt/minion/confd/scripts/remove-if-empty /opt/minion/etc/org.opennms.features.telemetry.listeners-udp-single-port.cfg"
